// ng-tv-focusable-example/src/app/views/example3.component.ts
import { Component, OnInit } from '@angular/core';
import { $tv } from 'ng-tv-focusable';
@Component({
  selector: 'app-example1',
  template: `
  <div class="demo">
    <span 
    *ngFor='let in of counter(30) ;let i = index' 
    [id]="i+1"
    class="span" focusable 
    (left)="left(i)" 
    (up)="up(i)" 
    (right)="right(i)" 
    (down)="down(i)" 
    (click)="enter(i)" 
    (onFocus)="focus(i, $event)" 
    (onBlur)="blur(i, $event)">
      {{i+1}}
      <i *ngIf="i == 3">按enter键触发click方法</i>
      <i *ngIf="i == 5">向下跳到18</i>
      <i *ngIf="i == 6">向上跳到18</i>
      <i *ngIf="i == 9">向左跳到18</i>
      <i *ngIf="i == 10">向右跳到18</i>
      <i *ngIf="i == 22">失去焦点时触发事件onBlur</i>
      <i *ngIf="i == 27">获取焦点时触发事件onFocus</i>
    </span>
  </div>
  `,
  styles: [`
  .demo{width:500px;}
    .span{
      display:inline-block;
      background:#6B9DFF;
      width:100px;
      height:100px;
      margin-left:20px;
      margin-top:20px;
      transition: all .5s;vertical-align: text-bottom
    }
    .focus{transform: scale(1.2);box-shadow: 0 0 20px blue}
  `],
})
export class Example3Component implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  counter(i: number) {
    return new Array(i);
  }

  left(index) {
    if(index === 9) {
      $tv.requestFocus($tv.getElementByPath('//div[@class="demo"]/span[18]'))
    }
  }

  up(index) {
    if(index === 6) {
      $tv.requestFocus($tv.getElementByPath('//div[@class="demo"]/span[18]'))
    }
  }

  right(index) {
    if(index === 10) {
      $tv.requestFocus($tv.getElementByPath('//div[@class="demo"]/span[18]'))
    }
  }

  down(index) {
    if(index === 5) {
      $tv.requestFocus($tv.getElementByPath('//div[@class="demo"]/span[18]'))
    }
  }

  enter(index) {
    if(index === 3) {
      alert('click');
    }
  }

  focus(index, $event) {
    if(index === 27) {
      alert(`第${28}个将要获取焦点了哦！`)
      console.log($event.detail.el);
    }
  }

  blur(index, $event) {
    if(index === 22) {
      alert(`第${23}个将要失去焦点了哦！`)
      console.log($event.detail.el);
    }
  }
}

// react-tv-focusable-example/src/views/example3.js
import React, {Component} from "react";
import '../common/public.css';
import {$tv} from 'react-tv-focusable'
class TvFocusable extends Component {
    componentDidMount() {
        $tv.init({
            focusableClassName:'r-focusable', // 必须配置项
        })
        const els = document.getElementsByClassName('r-focusable');
        for(let el of els) {
            // 自定义事件，名称一定要是和下面的名字对应哦
            el.addEventListener("left", this.left);
            el.addEventListener("right", this.right);
            el.addEventListener("up", this.up);
            el.addEventListener("down", this.down);
            el.addEventListener("onBlur", this.blur);
            el.addEventListener("onFocus", this.focus);
        }
    }

    componentWillUnmount() {
        const els = document.getElementsByClassName('r-focusable');
        for(let el of els) {
            el.removeEventListener("left", this.left);
            el.removeEventListener("right", this.right);
            el.removeEventListener("up", this.up);
            el.removeEventListener("down", this.down);
            el.removeEventListener("onBlur", this.blur);
            el.removeEventListener("onFocus", this.focus);
        }
    }

    left(event) {
        const index = event.target.getAttribute('index');
        if(Number(index) === 10){
            $tv.requestFocus($tv.getElementByPath('//div[@class="demo"]/span[18]'))
        }
    }
    right(event) {
        const index = event.target.getAttribute('index');
        if(Number(index) === 11){
            $tv.requestFocus($tv.getElementByPath('//div[@class="demo"]/span[18]'))
        }
    }
    up(event) {
        const index = event.target.getAttribute('index');
        if(Number(index) === 7){
            $tv.requestFocus($tv.getElementByPath('//div[@class="demo"]/span[18]'))
        }
    }
    down(event) {
        const index = event.target.getAttribute('index');
        if(Number(index) === 6){
            $tv.requestFocus($tv.getElementByPath('//div[@class="demo"]/span[18]'))    
        }
    }

    enter(index) {
        if(Number(index) === 4) {
            alert('click');
        }
    }
    
    focus(event) {
        const index = event.target.getAttribute('index');
        if(Number(index) === 28){
            alert(`第${28}个将要获取焦点了哦！`)
            console.log(event.detail.el);
        }
    }
    
    blur(event) {
        const index = event.target.getAttribute('index');
        if(Number(index) === 23){
            alert(`第${23}个将要失去焦点了哦！`)
            console.log(event.detail.el);
        }
    }
   
    render(){
        let lists = [];
        for(let i=0;i< 105;i++) {
            let str = '';
            if(i === 3) { str = '按enter键触发click方法'; };
            if(i === 5) { str = '向下跳到18'; };
            if(i === 6) { str = '向上跳到18'; };
            if(i === 9) { str = '向左跳到18'; };
            if(i === 10) { str = '向右跳到18'; };
            if(i === 22) { str = '失去焦点时触发事件onBlur'; };
            if(i === 27) { str = '获取焦点时触发事件onFocus'; };

            lists.push(<span 
                className="span r-focusable"
                onClick={() => this.enter(i+1)}
                index={i + 1}
                key={i}>
                    {i+1}<br/>
                    {str}
                </span>)
        }   
        
        return (
            <div className="demo">
                {lists}
            </div>
        )
    }
}


export default TvFocusable;
