// react-tv-focusable-example/src/App.js
import React, {Component} from "react";
import {
  BrowserRouter as Router,
  Switch,
  Route,
  NavLink
} from "react-router-dom";
import Example2 from './views/example2.js';
import Example1 from './views/example1';
import Example3 from './views/example3';
import Example4 from './views/example4';
import Example5 from './views/example5';
import Example6 from './views/example6';

import './common/public.css';

export default class App extends Component {

  render() {
    return (
        <Router>
          <div>
            <nav className="nav-box">
                <NavLink className="nav-item" activeClassName="active" to="/example1">设置元素可获取焦点(focusable)</NavLink>
                <NavLink className="nav-item" activeClassName="active" to="/example2">指定焦点移到到某一个元素上(ie)</NavLink>
                <NavLink className="nav-item" activeClassName="active" to="/example3">自定义焦点移动(自定义事件)</NavLink>
                <NavLink className="nav-item" activeClassName="active" to="/example4">$tv.init<br/>$tv.resetXXX</NavLink>
                <NavLink className="nav-item" activeClassName="active" to="/example5">局部滚动</NavLink>
                <NavLink className="nav-item" activeClassName="active" to="/example6">综合案例</NavLink>
            </nav>
    
            {/* A <Switch> looks through its children <Route>s and
                renders the first one that matches the current URL. */}
            <div className="app-contetn">
              <Switch>
                <Route path="/example1">
                  <Example1 />
                </Route>
                <Route path="/example2">
                  <Example2 />
                </Route>
                <Route path="/example3">
                  <Example3 />
                </Route>
                <Route path="/example4">
                  <Example4 />
                </Route>
                <Route path="/example5">
                  <Example5 />
                </Route>
                <Route path="/example6">
                  <Example6 />
                </Route>
              </Switch>
            </div>
          </div>
        </Router>
      );
    }
    
}

// ng-tv-focusable-example/src/app/app.component.ts
import { Component } from '@angular/core';
import { $tv } from 'ng-tv-focusable';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent {
  title = 'ng-tv-focusable-example';
  constructor() {
    // 可配置可不配置， 不做下面配置的情况下使用ng-tv-focusable默认的配置
    /**
      $tv.init({
        focusClassName: "config-focus", // 聚焦元素的className （默认focus）
        KEYS: {KEY_LEFT: [37], KEY_UP: [38], KEY_RIGHT: [39], KEY_DOWN: [40]}, // 自定义键值
        findFocusType: 1, //找焦点方式 0：直线上 1：最近（默认1） 
        initDis: 20 // 只有当findFocusType为0时才会生效，直线类型找焦点时，按键方向的交叉轴方向允许的最大找焦点范围,（默认20px）
      })
    */
  }
}

<div class="nav-box">
  <a class="nav-item" routerLink="/example1" routerLinkActive="active">设置元素可获取焦点(focusable)</a> 
  <a class="nav-item" routerLink="/example2" routerLinkActive="active">指定焦点移到到某一个元素上</a> 
  <a class="nav-item" routerLink="/example3" routerLinkActive="active">自定义焦点移动(自定义事件)</a> 
  <a class="nav-item" routerLink="/example4" routerLinkActive="active">$tv.init<br/>$tv.resetXXX</a> 
  <a class="nav-item" routerLink="/example5" routerLinkActive="active">局部滚动</a> 
  <a class="nav-item" routerLink="/example6" routerLinkActive="active">综合案例</a> 
</div>

<div class="app-contetn">
  <router-outlet></router-outlet>
</div>
